"""Add notes table

Revision ID: cd3ec49456e4
Revises: 
Create Date: 2026-02-17 23:01:43.396135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""Add notes table

Revision ID: cd3ec49456e4
Revises: 
Create Date: 2026-02-17 23:01:43.396135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd3ec49456e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all existing related tables to start fresh with the new note system
    op.execute("DROP TABLE IF EXISTS flashcards CASCADE")
    op.execute("DROP TABLE IF EXISTS problem_attempts CASCADE")
    op.execute("DROP TABLE IF EXISTS note_blocks CASCADE")
    op.execute("DROP TABLE IF EXISTS note_tags CASCADE")
    op.execute("DROP TABLE IF EXISTS tags CASCADE")
    op.execute("DROP TABLE IF EXISTS notes CASCADE")
    
    # Recreate notes table
    op.create_table('notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('content', sa.JSON(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_title'), 'notes', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notes', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('notes_parent_id_fkey'), 'notes', 'notes', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('notes_problem_id_fkey'), 'notes', 'problems', ['problem_id'], ['id'])
    op.alter_column('notes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('notes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('notes', 'content')
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tags_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tags_pkey'))
    )
    op.create_table('note_tags',
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('note_tags_note_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('note_tags_tag_id_fkey')),
    sa.PrimaryKeyConstraint('note_id', 'tag_id', name=op.f('note_tags_pkey'))
    )
    op.create_table('problem_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('problem_attempts_problem_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('problem_attempts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('problem_attempts_pkey'))
    )
    op.create_table('flashcards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('front', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('back', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('next_review_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('interval', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ease_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('flashcards_note_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('flashcards_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('flashcards_pkey'))
    )
    op.create_table('note_blocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('note_blocks_note_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('note_blocks_pkey'))
    )
    # ### end Alembic commands ###
